# Data Retrieval Task
data_retrieval_task:
  description: |
    Given a patient identifier, a start date and optionally an end date (which defaults to today if not provided),
    use your tools to retrieve patient data from the database. Reformat this data in a manner suitable for 
    other agents to use for interpeting where on the Referral to Treament pathway the patient is.
    Do not make any interpretations yourself. Do not generate any data yourself.
    Only use the data provided by the database.
    If no data is found, return an empty JSON array: []
    
    Patient Identifier: {person_id}
    Start Date: {start_date}
    End Date: {end_date}
  expected_output: |
    A JSON array of notes as returned by the database but with improved formatting. 
    It should be ordered by date with the oldest notes appearing first.
    eg. 
        "note_date": "2023-10-01",
        "note_text": "Original note text here...",
        "department": "Cardiology",
        "note_type": "Clinic Letter"

    If no data is found, return an empty JSON array: []
    
  agent: data_retrieval_agent
  

# Clock Start Task
data_intent_task:
  description: |
    You will receive a JSON array of patient notes and related information. 
    These will be ordered by date. These will contain a variety of information including clinic letters, EHR notes, test results and other information. 
    Some of these notes will be clinic letters dictated by a hospital clinician to another clinician, typically a general practitioner. The patient is being seen in a hospital service for assessment and/or treatment. 
    Your task is to determine the intent in these letters based on NHS England RTT guidelines.
    **Note**: Not all letters will indicate that a "clock start event" or a "clock stop event" has occurred as per NHS England RTT guidelines. Some letters may be follow-up letters after a previous initial consultation, others may contain information about the patient's condition, treatment plan, and any further referrals or investigations that may be required. Some maybe unrelated to RTT entirely or notes made in the EHR by administrative staff. 

    You will determine the intent of these letters and will classify them as one of the following:
    - Discharged to GP
    - Referred to another consultant or service
    - Active monitoring started
    - Active monitoring continued
    - Added to waiting list for a procedure
    - investigations or tests ordered

    A letter may contain multiple intents. If you are unsure, use your best judgement based on the content of the letter and the context provided by previous letters. You may return more than one intent per letter. If there is no clear intent, return "No clear intent".


    
  expected_output: |
    A JSON array of objects, each containing the original note and an array of identified intents. 
    For example:
    [
      {
        "note_date": "2023-10-01",
        "note_id": "12345",
        "note_text": "Original note text here...",
        "department": "Cardiology",
        "note_type": "Clinic Letter",
        "intents": ["Referred to another consultant or service", "Investigations or tests ordered"]
      },
      ...
    ]
  agent: data_intent_agent
  allow_delegation: true


# Clock Stop Task
clock_stop_task:
  description: |
    Your task is to determine if the information provided has any evidence that qualifies as a "clock stop event" based on NHS England guidelines.
    You will receive a json array of patient notes and related information. These will be ordered by date. These will contain a variety of information including clinic letters, EHR notes, test results and other information. Some of these notes will be clinic letters dictated by a hospital clinician to another clinician, typically a general practitioner. The patient is being seen in a hospital service for assessment and/or treatment.
    These will also have one or more identified intents as classified by the data intent agent.
    Your task is to determine if any of these letters qualify as a "clock stop event" based on NHS England RTT guidelines.
    **Note**: Not all letters will indicate that a "clock stop event" has occurred as per NHS England RTT guidelines. Some letters may be follow-up letters after a previous initial consultation, others may contain information about the patient's condition, treatment plan, and any further referrals or investigations that may be required. Some maybe unrelated to RTT entirely or notes made in the EHR by administrative staff.
    A clock stop event is defined as follows:
    **1)** A clock stops when:
       a) First definitive treatment starts. This could be:
          i. Treatment provided by an interface service;
          ii. Treatment provided by a consultant-led service;
          iii. Therapy or healthcare science intervention provided in secondary care or at an interface service, if this is what the consultant-led or interface service decides is the best way to manage the patient's disease, condition or injury and avoid further interventions;
       b) A clinical decision is made and has been communicated to the patient, and subsequently their GP and/or other referring practitioner without undue delay, to add a patient to a transplant list.

    **Clock stops for 'non-treatment'**

    **2)** A waiting time clock stops when it is communicated to the patient, and subsequently their GP and/or other referring practitioner without undue delay that:
       a) It is clinically appropriate to return the patient to primary care for any non consultant-led treatment in primary care;
       b) A clinical decision is made to start a period of active monitoring;
       c) A patient declines treatment having been offered it;
       d) A clinical decision is made not to treat;
       e) A patient DNAs their first appointment following the initial referral that started their waiting time clock, provided that the provider can demonstrate that the appointment was clearly communicated to the patient¹⁰;
       f) A patient DNAs any other appointment and is subsequently discharged back to the care of their GP, provided that:
          i. the provider can demonstrate that the appointment was clearly communicated to the patient;
          ii. discharging the patient is not contrary to their best clinical interests;
          iii. discharging the patient is carried out according to local, publicly available/published, policies on DNAs;
          iv. These local policies are clearly defined and specifically protect the clinical interests of vulnerable patients (e.g. children) and are agreed with clinicians, commissioners, patients and other relevant stakeholders.

    
  expected_output: |
    A clear "Yes" or "No" answer indicating whether any of the letters qualifies as a clock stop event, along with a brief explanation of the reasoning behind the decision.
    Return a JSON array of objects, each containing the original note, identified intents and whether it qualifies as a clock stop event.
    For example:
    [
      {
        "note_date": "2023-10-01",
        "note_id": "12345",
        "note_text": "Original note text here...",
        "department": "Cardiology",
        "note_type": "Clinic Letter",
        "intents": ["Referred to another consultant or service", "Investigations or tests ordered"],
        "clock_stop_event": "No"
      },
      ...
    ]
  agent: clock_stop_analyst
  allow_delegation: true
